### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by johnomotani** [boutproject/boutdata#27]
See discussion on https://github.com/boutproject/BOUT-dev/issues/2151

**Comment by loeiten** [comment]
Shoot...I accidentally managed to push to the `master` branch. It looks like the enforcement to go through a PR was not applying to admins (I changed it now so that it won't happen again). In order to revert back I need to change some permissions. @johnomotani: Would you have the possibility to check through my commit and see if everything is OK, if not I will revert and make a formal PR

**Comment by johnomotani** [comment]
I think it's OK, but we should copy whatever updates we make in https://github.com/boutproject/boututils/pull/18 eventually. It has disabled the Travis check - @loeiten could you switch the required checks from Travis to the new Github Actions so I can merge #29 please?

**Comment by loeiten** [comment]
Great 👍. I've created #30 for updates from https://github.com/boutproject/boututils/pull/18.
I've also updated the checks so that only the GitHub action tests need to pass (i.e. travis no longer need to pass)
