### ISSUE TITLE
black CI

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/boutdata#61]
I would prefer to have the black CI fix issues, rather then complain.
This is especially annoying if black changes things ...

**Comment by johnomotani** [comment]
Agree to some extent, but letting the CI commit `black` changes has the potential to cause other issues...

E.g. 1) work on some branch; 2) push branch to github; 3) work some more; 4) push again -> merge conflict due to black changes.

Another (much) less important reason to prefer just complaining is that auto-fixes would lead to more 'black format' commits in the history. I quite often find myself doing something like 1) write commit; 2) push; 3) black CI fails; 4) run black, `git commit --amend`, `git push -f`. That workflow keeps the history slightly cleaner.

On balance, I'd be inclined to leave the black CI as-is.

**Comment by dschwoerer** [comment]
> E.g. 1) work on some branch; 2) push branch to github; 3) work some more; 4) push again -> merge conflict due to black changes.

You can still `push -f` - and this time black format before hand :-)

> Another (much) less important reason to prefer just complaining is that auto-fixes would lead to more 'black format' commits in the history. I quite often find myself doing something like 1) write commit; 2) push; 3) black CI fails; 4) run black, `git commit --amend`, `git push -f`. That workflow keeps the history slightly cleaner.

It doesn't prevent you from doing that :-)
But additionally, you can also pull + squash with `rebase -i` and push -f. It is just as clean. And you don't have to have all the linter/formatter installed in that version that the project has set up ...

> On balance, I'd be inclined to leave the black CI as-is.

I find it nicer, but feel free to close this as wont-fix ;-)

**Comment by johnomotani** [comment]
you have good points there @dschwoerer! Also, we can always squash-merge if the history in some PR gets messy. So I've changed my mind - I'm open to having the black CI commit its changes if someone wants to implement.

**Comment by ZedThree** [comment]
I'm also in favour of having it applied automatically -- one less thing to think about :)
